default_stages: [pre-commit, pre-push]
repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.5.13
    hooks:
      - id: uv-lock
        stages: [pre-commit]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        stages: [pre-commit]
      - id: ruff-format
        stages: [pre-commit]

  - repo: local
    hooks:
      - id: pyright
        name: pyright
        language: system
        entry: uv run pyright
        stages: [pre-push]
        pass_filenames: false

      - id: pytest
        name: pytest
        entry: uv run pytest
        stages: [pre-push]
        language: system
        pass_filenames: false
