default_stages: [pre-commit, pre-push]
repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.5.13
    hooks:
      - id: uv-lock
        stages: [pre-commit]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        stages: [pre-commit]
      - id: ruff-format
        stages: [pre-commit]

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.391
    hooks:
      - id: pyright
        entry: uv run pyright
        stages: [pre-push]

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: uv run pytest tests
        stages: [pre-push]
        language: python
        pass_filenames: false
        always_run: true
