[project]
name = "py-ur"
version = "0.1.0"
description = "Python app to communicate with Universal Robot (tested with UR3, UR5)"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["pyyaml>=6.0.2"]

[tool.uv.workspace]
